int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(char c);
int _isalpha(char c);
int print_sign(int n);
int _abs(int n);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int,int);
void print_to_98(int);
void positive_or_negative(int i);
int largest_number(int a, int b, int c);
int convert_day(int, int);
void print_remaining_days(int, int, int);
int _putchar(char);
int _isupper(char);
int _isdigit(int);
int mul(int, int);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int);
void print_diagonal(int);
void print_square(int size);
void print_triangle(int size);
void reset_to_98(int*);
void swap_int(int*, int*);
int _strlen(char *str);
void _puts(char *str);
void print_rev(char *c);
void rev_string(char *s);
void puts2(char *str);
void puts_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest, char *src);
char *_strcat(char *dest, char *src);
char *_strncat(char *dest, char *src, int n);
char *_strncpy(char *dest, char *src, int n);
int _strcmp(char *s1, char *s2);
void reverse_array(int *a, int n);
char *string_toupper(char *str);
char *cap_string(char *s);
char *leet(char *s);
char *_memset(char *s, char b, unsigned int n);
char *_memcpy(char *dest, char *src, unsigned int n);
char *_strchr(char *s, char c);
int _strpson(char *s, char *accept);
char *_strpbrk(char *s, char *accept);
char *_strstr(char *haystack, char *needle);
void print_chessboard(char (*a)[8]);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _sqrt_recursion_helper(int i, int n);
int _sqrt_recursion(int n);
int recursive_prime_helper(int n, int i);
int is_prime_number(int n);
